### ISSUE TITLE
tailwind pluginForms

### ISSUE THREAD

**Issue by Coffee-kitten** [JingBh/ServerStatus-theme#1]
想请教一下作者哪个组件有用到Forms插件吗，由于daisyui和原码中的Forms插件有冲突，想使用daisyui要删掉Forms

**Comment by JingBh** [comment]
你好，我刚才试了一下，如果去掉 forms 插件，“一键部署命令生成”页面中 checkbox 的样式会有变化。

由于这个主题是我个人使用，最开始做的时候没有考虑那么多，也不太可能再花时间进行修改适配。

如果你有定制的需求，欢迎 fork 后作修改！

**Comment by Coffee-kitten** [comment]
明白！谢谢作者回复
