### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Yizelove** [JingBh/ServerStatus-theme#2]
可否像[ServerStatus-Theme-Light](https://github.com/orilights/ServerStatus-Theme-Light#使用)一样直接在Release中提供已经打包好的主题代码，直接替换即可？

**Comment by JingBh** [comment]
已添加

**Comment by Yizelove** [comment]
感谢大佬

**Comment by JingBh** [comment]
现在移到 GitHub Actions 里面了，之后的新 commit 都会自动构建 assets，上传到 artifacts 里面；这样可能也比较公开透明一点

**Comment by Yizelove** [comment]
> 现在移到 GitHub Actions 里面了，之后的新 commit 都会自动构建 assets，上传到 artifacts 里面；这样可能也比较公开透明一点

好的👌
