### ISSUE TITLE
页端建议

### ISSUE THREAD

**Issue by Yizelove** [JingBh/ServerStatus-theme#3]
位置那里我觉得使用国旗图片或者emoji好些，可以英文缩写自动转换的那种，类似原版。

另外此主题好像没有切换夜间模式的功能(手机端)，能否加上？

还有首页顶部黑色的那块感觉有点高(手机端)，不是很美观，建议改短点，占页面的6-10%好点。

最后，One-Click功能实测好像并不能用，生成的链接访问返回404(使用此主题) & 401(原版)，不知是Release中编译好的不完整还是我的配置问题。

祝你度过愉快的一天！

**Comment by JingBh** [comment]
你好！

这个主题本来是我根据自己需求写的，只是顺便开源在了 GitHub 上；没想到被 ServerStatus-Rust 项目官方收录了，但是本质上还是供个人使用的项目，所以我不太可能花时间在更新这个项目上。如果你有定制化的需求，欢迎 fork 后自行修改。

---

关于你提出的问题：

> 位置那里我觉得使用国旗图片或者emoji好些，可以英文缩写自动转换的那种，类似原版。

这个确实是我疏忽了，没注意到原版有这个功能，有时间会加上。

> 此主题好像没有切换夜间模式的功能(手机端)，能否加上？

会根据设备系统主题自动切换，没有做手动切换按钮。

> One-Click功能实测好像并不能用，生成的链接访问返回404(使用此主题) & 401(原版)

生成的链接是 `域名` + `/i`，这条路由是 ServerStatus-Rust 服务端提供的，与主题无关。我这里不清楚你的具体配置，如果 ServerStatus-Rust 部署在非根目录，确实可能有问题。

**Comment by Yizelove** [comment]
感谢你的解答
